// Achievement definitions
export const ACHIEVEMENT_DEFS = [
	{
		key: "first_save",
		title: "Primer Ahorro",
		description: "Completa tu primera celda",
		icon: "🌱",
		condition: "Completar 1 celda",
	},
	{
		key: "ten_cells",
		title: "Constancia",
		description: "Completa 10 celdas",
		icon: "💪",
		condition: "Completar 10 celdas",
	},
	{
		key: "fifty_cells",
		title: "Medio Camino",
		description: "Completa 50 celdas",
		icon: "🏅",
		condition: "Completar 50 celdas",
	},
	{
		key: "first_plan",
		title: "Soñador",
		description: "Crea tu primer plan",
		icon: "✨",
		condition: "Crear 1 plan",
	},
	{
		key: "first_100k",
		title: "Ahorrador Inicial",
		description: "Acumula $100.000",
		icon: "🥉",
		condition: "Ahorrar $100.000",
	},
	{
		key: "first_500k",
		title: "Ahorrador Intermedio",
		description: "Acumula $500.000",
		icon: "🥈",
		condition: "Ahorrar $500.000",
	},
	{
		key: "first_1m",
		title: "Master Saver",
		description: "Acumula $1.000.000",
		icon: "🥇",
		condition: "Ahorrar $1.000.000",
	},
	{
		key: "streak_3",
		title: "Racha de 3",
		description: "3 días seguidos ahorrando",
		icon: "🔥",
		condition: "Racha de 3 días",
	},
	{
		key: "streak_7",
		title: "Semana Perfecta",
		description: "7 días seguidos ahorrando",
		icon: "⚡",
		condition: "Racha de 7 días",
	},
	{
		key: "streak_30",
		title: "Leyenda Mensual",
		description: "30 días seguidos ahorrando",
		icon: "🏆",
		condition: "Racha de 30 días",
	},
	{
		key: "plan_complete",
		title: "Objetivo Cumplido",
		description: "Completa un plan de ahorro",
		icon: "🎉",
		condition: "Completar 1 plan",
	},
	{
		key: "five_plans",
		title: "Planificador Pro",
		description: "Crea 5 planes",
		icon: "📋",
		condition: "Crear 5 planes",
	},
];
